# Generated by Django 5.0.1 on 2024-01-21 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_friendinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='friendship',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
