# Generated by Django 5.0.1 on 2024-01-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_friendinvitation_current_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinvitation',
            name='status',
        ),
    ]
