# Generated by Django 5.0.1 on 2024-01-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_rename_accepted_friendrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendInvitation',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
